### ISSUE TITLE
Error Summoning Eik

### ISSUE THREAD

**Issue by myceliated** [probablykory/useful-trophies#2]
Trying to use the deer trophys on eikthyr summoning alter does not use them, and throws errors in console.

Love the mod thanks for doing stuff with it.

**Comment by probablykory** [comment]
The version I just published, 1.0.1, should resolve the exception getting thrown.  There's still a bug, where you'll now summon Eik *and* get a short boss power buff.  I'll have a fix for that soon.

**Comment by probablykory** [comment]
Published 1.0.2, which now prevents consuming summoning items when in proximity to the offering bowl they're used in.  If players want a buff while fighting a boss, they'll need to consume an extra item at least 10m away from the offering bowl.
