### ISSUE TITLE
newest update throws this error

### ISSUE THREAD

**Issue by Xode007** [probablykory/useful-trophies#4]
[Error  : Unity Log] FieldAccessException: Field `MessageHud:m_instance' is inaccessible from method `UsefulTrophies.UsefulTrophies:DetectAndWhitelistSkills (Player)'

Stack trace:
UsefulTrophies.Patches.PlayerOnLoad (Player __instance) (at <06bb35c9ffb3444db18fb6e633635194>:0)
(wrapper dynamic-method) Player.DMD<Player::Load>(Player,ZPackage)
(wrapper dynamic-method) PlayerProfile.DMD<PlayerProfile::LoadPlayerData>(PlayerProfile,Player)
(wrapper dynamic-method) Game.DMD<Game::SpawnPlayer>(Game,UnityEngine.Vector3)
Game.UpdateRespawn (System.Single dt) (at <0c7c9e9f999940deaf2bdbbf6e7b2314>:0)
Game.FixedUpdate () (at <0c7c9e9f999940deaf2bdbbf6e7b2314>:0)

end result is the game is unplayable because my avatar just spins at its spawn point and i cant move or do anything in game. The previous version before the most recent update did not do this. I downgraded back to 1.0.5 and the error vanished.

**Comment by probablykory** [comment]
UsefulTrophies v1.0.7 just released on thunderstore, and that should fix this issue.
